#define kInAirDeviceDidConnectToTheSameWifiNotification @"InAirDeviceDidConnectToWifiNotification"
#define kInAirConnectedToSelectedWifiNotification @"InAirConnectedToSelectedWifiNotification"
#define kNetworkSSIDKey @"NetworkSSIDKey"