// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

// @@protoc_insertion_point(imports)

@class Device;
@class DeviceBuilder;
@class DeviceEvent;
@class DeviceEventBuilder;
@class Event;
@class EventBuilder;
@class FunctionEvent;
@class FunctionEventBuilder;
@class GestureEvent;
@class GestureEventBuilder;
@class HandMotionEvent;
@class HandMotionEventBuilder;
@class KeypressEvent;
@class KeypressEventBuilder;
@class MotionEvent;
@class MotionEventBuilder;
@class OAuthRequestEvent;
@class OAuthRequestEventBuilder;
@class OAuthResponseEvent;
@class OAuthResponseEventBuilder;
@class SetupRequestEvent;
@class SetupRequestEventBuilder;
@class SetupResponseEvent;
@class SetupResponseEventBuilder;
@class TextInputRequestEvent;
@class TextInputRequestEventBuilder;
@class TextInputResponseEvent;
@class TextInputResponseEventBuilder;
@class TouchEvent;
@class TouchEventBuilder;
@class WifiNetwork;
@class WifiNetworkBuilder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif

typedef NS_ENUM(SInt32, Phase) {
  PhaseBegan = 0,
  PhaseMoved = 1,
  PhaseStationary = 2,
  PhaseEnded = 3,
  PhaseCancelled = 4,
};

BOOL PhaseIsValidValue(Phase value);

typedef NS_ENUM(SInt32, SetupPhase) {
  SetupPhaseRequestCode = 0,
  SetupPhaseVerifyCode = 1,
  SetupPhaseRequestRename = 2,
  SetupPhaseRequestWifiScan = 3,
  SetupPhaseRequestWifiSelect = 4,
  SetupPhaseRequestWifiConnect = 5,
};

BOOL SetupPhaseIsValidValue(SetupPhase value);

typedef NS_ENUM(SInt32, EventType) {
  EventTypeDevice = 0,
  EventTypeTouch = 1,
  EventTypeMotion = 2,
  EventTypeKeypress = 3,
  EventTypeGesture = 4,
  EventTypeHandMotion = 5,
  EventTypeHandGesture = 6,
  EventTypeOauthRequest = 7,
  EventTypeOauthResponse = 8,
  EventTypeSetupRequest = 9,
  EventTypeSetupResponse = 10,
  EventTypeTextInputRequest = 11,
  EventTypeTextInputResponse = 12,
  EventTypeFunctionEvent = 13,
};

BOOL EventTypeIsValidValue(EventType value);

typedef NS_ENUM(SInt32, DeviceVendor) {
  DeviceVendorIos = 0,
  DeviceVendorAndroid = 1,
  DeviceVendorLeapmotion = 2,
  DeviceVendorKinect = 3,
  DeviceVendorWindows = 4,
  DeviceVendorOther = 5,
};

BOOL DeviceVendorIsValidValue(DeviceVendor value);

typedef NS_ENUM(SInt32, DeviceEventType) {
  DeviceEventTypeRegister = 0,
  DeviceEventTypeUnregister = 1,
};

BOOL DeviceEventTypeIsValidValue(DeviceEventType value);

typedef NS_ENUM(SInt32, MotionEventType) {
  MotionEventTypeShake = 0,
};

BOOL MotionEventTypeIsValidValue(MotionEventType value);

typedef NS_ENUM(SInt32, KeypressEventState) {
  KeypressEventStateDown = 0,
  KeypressEventStateUp = 1,
};

BOOL KeypressEventStateIsValidValue(KeypressEventState value);

typedef NS_ENUM(SInt32, GestureEventType) {
  GestureEventTypeTap = 0,
  GestureEventTypePinch = 1,
  GestureEventTypePan = 2,
  GestureEventTypeSwipe = 3,
  GestureEventTypeRotation = 4,
  GestureEventTypeLongpress = 5,
  GestureEventTypeCircle = 6,
  GestureEventTypeWave = 7,
};

BOOL GestureEventTypeIsValidValue(GestureEventType value);

typedef NS_ENUM(SInt32, GestureEventState) {
  GestureEventStatePossible = 0,
  GestureEventStateBegan = 1,
  GestureEventStateChanged = 2,
  GestureEventStateEnded = 3,
  GestureEventStateCancelled = 4,
  GestureEventStateFailed = 5,
};

BOOL GestureEventStateIsValidValue(GestureEventState value);

typedef NS_ENUM(SInt32, GestureEventSwipeDirection) {
  GestureEventSwipeDirectionRight = 0,
  GestureEventSwipeDirectionLeft = 1,
  GestureEventSwipeDirectionUp = 2,
  GestureEventSwipeDirectionDown = 3,
  GestureEventSwipeDirectionForward = 4,
  GestureEventSwipeDirectionBackward = 5,
};

BOOL GestureEventSwipeDirectionIsValidValue(GestureEventSwipeDirection value);

typedef NS_ENUM(SInt32, GestureEventCircleDirection) {
  GestureEventCircleDirectionClockwise = 0,
  GestureEventCircleDirectionCounterClockwise = 1,
};

BOOL GestureEventCircleDirectionIsValidValue(GestureEventCircleDirection value);

typedef NS_ENUM(SInt32, HandMotionEventState) {
  HandMotionEventStateOpen = 0,
  HandMotionEventStateGrab = 1,
  HandMotionEventStatePinch = 2,
};

BOOL HandMotionEventStateIsValidValue(HandMotionEventState value);

typedef NS_ENUM(SInt32, TextInputRequestEventType) {
  TextInputRequestEventTypeText = 0,
  TextInputRequestEventTypePassword = 1,
};

BOOL TextInputRequestEventTypeIsValidValue(TextInputRequestEventType value);

typedef NS_ENUM(SInt32, TextInputResponseEventState) {
  TextInputResponseEventStateBegan = 0,
  TextInputResponseEventStateChanged = 1,
  TextInputResponseEventStateEnded = 2,
  TextInputResponseEventStateCancelled = 3,
};

BOOL TextInputResponseEventStateIsValidValue(TextInputResponseEventState value);

typedef NS_ENUM(SInt32, FunctionEventKey) {
  FunctionEventKeyF1 = 0,
  FunctionEventKeyF2 = 1,
  FunctionEventKeyF3 = 2,
  FunctionEventKeyF4 = 3,
  FunctionEventKeyMediaPlay = 4,
  FunctionEventKeyMediaPause = 5,
  FunctionEventKeyMediaFastForward = 6,
  FunctionEventKeyMediaRewind = 7,
  FunctionEventKeyMediaStop = 8,
};

BOOL FunctionEventKeyIsValidValue(FunctionEventKey value);


@interface ProtoRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface Event : PBExtendableMessage {
@private
  BOOL hasTimestamp_:1;
  BOOL hasTrackingAreaWidth_:1;
  BOOL hasTrackingAreaHeight_:1;
  BOOL hasTarget_:1;
  BOOL hasReplyTo_:1;
  BOOL hasType_:1;
  SInt64 timestamp;
  SInt32 trackingAreaWidth;
  SInt32 trackingAreaHeight;
  NSString* target;
  NSString* replyTo;
  EventType type;
}
- (BOOL) hasType;
- (BOOL) hasTimestamp;
- (BOOL) hasTrackingAreaWidth;
- (BOOL) hasTrackingAreaHeight;
- (BOOL) hasTarget;
- (BOOL) hasReplyTo;
@property (readonly) EventType type;
@property (readonly) SInt64 timestamp;
@property (readonly) SInt32 trackingAreaWidth;
@property (readonly) SInt32 trackingAreaHeight;
@property (readonly, strong) NSString* target;
@property (readonly, strong) NSString* replyTo;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (EventBuilder*) builder;
+ (EventBuilder*) builder;
+ (EventBuilder*) builderWithPrototype:(Event*) prototype;
- (EventBuilder*) toBuilder;

+ (Event*) parseFromData:(NSData*) data;
+ (Event*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Event*) parseFromInputStream:(NSInputStream*) input;
+ (Event*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Event*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Event*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface EventBuilder : PBExtendableMessageBuilder {
@private
  Event* resultEvent;
}

- (Event*) defaultInstance;

- (EventBuilder*) clear;
- (EventBuilder*) clone;

- (Event*) build;
- (Event*) buildPartial;

- (EventBuilder*) mergeFrom:(Event*) other;
- (EventBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (EventBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasType;
- (EventType) type;
- (EventBuilder*) setType:(EventType) value;
- (EventBuilder*) clearType;

- (BOOL) hasTimestamp;
- (SInt64) timestamp;
- (EventBuilder*) setTimestamp:(SInt64) value;
- (EventBuilder*) clearTimestamp;

- (BOOL) hasTrackingAreaWidth;
- (SInt32) trackingAreaWidth;
- (EventBuilder*) setTrackingAreaWidth:(SInt32) value;
- (EventBuilder*) clearTrackingAreaWidth;

- (BOOL) hasTrackingAreaHeight;
- (SInt32) trackingAreaHeight;
- (EventBuilder*) setTrackingAreaHeight:(SInt32) value;
- (EventBuilder*) clearTrackingAreaHeight;

- (BOOL) hasTarget;
- (NSString*) target;
- (EventBuilder*) setTarget:(NSString*) value;
- (EventBuilder*) clearTarget;

- (BOOL) hasReplyTo;
- (NSString*) replyTo;
- (EventBuilder*) setReplyTo:(NSString*) value;
- (EventBuilder*) clearReplyTo;
@end

@interface Device : PBGeneratedMessage {
@private
  BOOL hasHasKeyboard_:1;
  BOOL hasVersion_:1;
  BOOL hasName_:1;
  BOOL hasProductId_:1;
  BOOL hasVendor_:1;
  BOOL hasKeyboard_:1;
  SInt32 version;
  NSString* name;
  NSString* productId;
  DeviceVendor vendor;
}
- (BOOL) hasName;
- (BOOL) hasVendor;
- (BOOL) hasVersion;
- (BOOL) hasProductId;
- (BOOL) hasHasKeyboard;
@property (readonly, strong) NSString* name;
@property (readonly) DeviceVendor vendor;
@property (readonly) SInt32 version;
@property (readonly, strong) NSString* productId;
- (BOOL) hasKeyboard;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (DeviceBuilder*) builder;
+ (DeviceBuilder*) builder;
+ (DeviceBuilder*) builderWithPrototype:(Device*) prototype;
- (DeviceBuilder*) toBuilder;

+ (Device*) parseFromData:(NSData*) data;
+ (Device*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Device*) parseFromInputStream:(NSInputStream*) input;
+ (Device*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Device*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Device*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface DeviceBuilder : PBGeneratedMessageBuilder {
@private
  Device* resultDevice;
}

- (Device*) defaultInstance;

- (DeviceBuilder*) clear;
- (DeviceBuilder*) clone;

- (Device*) build;
- (Device*) buildPartial;

- (DeviceBuilder*) mergeFrom:(Device*) other;
- (DeviceBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (DeviceBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (DeviceBuilder*) setName:(NSString*) value;
- (DeviceBuilder*) clearName;

- (BOOL) hasVendor;
- (DeviceVendor) vendor;
- (DeviceBuilder*) setVendor:(DeviceVendor) value;
- (DeviceBuilder*) clearVendor;

- (BOOL) hasVersion;
- (SInt32) version;
- (DeviceBuilder*) setVersion:(SInt32) value;
- (DeviceBuilder*) clearVersion;

- (BOOL) hasProductId;
- (NSString*) productId;
- (DeviceBuilder*) setProductId:(NSString*) value;
- (DeviceBuilder*) clearProductId;

- (BOOL) hasHasKeyboard;
- (BOOL) hasKeyboard;
- (DeviceBuilder*) setHasKeyboard:(BOOL) value;
- (DeviceBuilder*) clearHasKeyboard;
@end

@interface DeviceEvent : PBGeneratedMessage {
@private
  BOOL hasDevice_:1;
  BOOL hasType_:1;
  Device* device;
  DeviceEventType type;
}
- (BOOL) hasType;
- (BOOL) hasDevice;
@property (readonly) DeviceEventType type;
@property (readonly, strong) Device* device;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

+ (id<PBExtensionField>) event;
- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (DeviceEventBuilder*) builder;
+ (DeviceEventBuilder*) builder;
+ (DeviceEventBuilder*) builderWithPrototype:(DeviceEvent*) prototype;
- (DeviceEventBuilder*) toBuilder;

+ (DeviceEvent*) parseFromData:(NSData*) data;
+ (DeviceEvent*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DeviceEvent*) parseFromInputStream:(NSInputStream*) input;
+ (DeviceEvent*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DeviceEvent*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (DeviceEvent*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface DeviceEventBuilder : PBGeneratedMessageBuilder {
@private
  DeviceEvent* resultDeviceEvent;
}

- (DeviceEvent*) defaultInstance;

- (DeviceEventBuilder*) clear;
- (DeviceEventBuilder*) clone;

- (DeviceEvent*) build;
- (DeviceEvent*) buildPartial;

- (DeviceEventBuilder*) mergeFrom:(DeviceEvent*) other;
- (DeviceEventBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (DeviceEventBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasType;
- (DeviceEventType) type;
- (DeviceEventBuilder*) setType:(DeviceEventType) value;
- (DeviceEventBuilder*) clearType;

- (BOOL) hasDevice;
- (Device*) device;
- (DeviceEventBuilder*) setDevice:(Device*) value;
- (DeviceEventBuilder*) setDeviceBuilder:(DeviceBuilder*) builderForValue;
- (DeviceEventBuilder*) mergeDevice:(Device*) value;
- (DeviceEventBuilder*) clearDevice;
@end

@interface TouchEvent : PBGeneratedMessage {
@private
  BOOL hasLocationX_:1;
  BOOL hasLocationY_:1;
  BOOL hasPhase_:1;
  Float32 locationX;
  Float32 locationY;
  Phase phase;
}
- (BOOL) hasLocationX;
- (BOOL) hasLocationY;
- (BOOL) hasPhase;
@property (readonly) Float32 locationX;
@property (readonly) Float32 locationY;
@property (readonly) Phase phase;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

+ (id<PBExtensionField>) event;
- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TouchEventBuilder*) builder;
+ (TouchEventBuilder*) builder;
+ (TouchEventBuilder*) builderWithPrototype:(TouchEvent*) prototype;
- (TouchEventBuilder*) toBuilder;

+ (TouchEvent*) parseFromData:(NSData*) data;
+ (TouchEvent*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TouchEvent*) parseFromInputStream:(NSInputStream*) input;
+ (TouchEvent*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TouchEvent*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TouchEvent*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TouchEventBuilder : PBGeneratedMessageBuilder {
@private
  TouchEvent* resultTouchEvent;
}

- (TouchEvent*) defaultInstance;

- (TouchEventBuilder*) clear;
- (TouchEventBuilder*) clone;

- (TouchEvent*) build;
- (TouchEvent*) buildPartial;

- (TouchEventBuilder*) mergeFrom:(TouchEvent*) other;
- (TouchEventBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TouchEventBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasLocationX;
- (Float32) locationX;
- (TouchEventBuilder*) setLocationX:(Float32) value;
- (TouchEventBuilder*) clearLocationX;

- (BOOL) hasLocationY;
- (Float32) locationY;
- (TouchEventBuilder*) setLocationY:(Float32) value;
- (TouchEventBuilder*) clearLocationY;

- (BOOL) hasPhase;
- (Phase) phase;
- (TouchEventBuilder*) setPhase:(Phase) value;
- (TouchEventBuilder*) clearPhase;
@end

@interface MotionEvent : PBGeneratedMessage {
@private
  BOOL hasType_:1;
  MotionEventType type;
}
- (BOOL) hasType;
@property (readonly) MotionEventType type;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

+ (id<PBExtensionField>) event;
- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MotionEventBuilder*) builder;
+ (MotionEventBuilder*) builder;
+ (MotionEventBuilder*) builderWithPrototype:(MotionEvent*) prototype;
- (MotionEventBuilder*) toBuilder;

+ (MotionEvent*) parseFromData:(NSData*) data;
+ (MotionEvent*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MotionEvent*) parseFromInputStream:(NSInputStream*) input;
+ (MotionEvent*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MotionEvent*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MotionEvent*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MotionEventBuilder : PBGeneratedMessageBuilder {
@private
  MotionEvent* resultMotionEvent;
}

- (MotionEvent*) defaultInstance;

- (MotionEventBuilder*) clear;
- (MotionEventBuilder*) clone;

- (MotionEvent*) build;
- (MotionEvent*) buildPartial;

- (MotionEventBuilder*) mergeFrom:(MotionEvent*) other;
- (MotionEventBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MotionEventBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasType;
- (MotionEventType) type;
- (MotionEventBuilder*) setType:(MotionEventType) value;
- (MotionEventBuilder*) clearType;
@end

@interface KeypressEvent : PBGeneratedMessage {
@private
  BOOL hasKeycode_:1;
  BOOL hasState_:1;
  SInt32 keycode;
  KeypressEventState state;
}
- (BOOL) hasState;
- (BOOL) hasKeycode;
@property (readonly) KeypressEventState state;
@property (readonly) SInt32 keycode;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

+ (id<PBExtensionField>) event;
- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (KeypressEventBuilder*) builder;
+ (KeypressEventBuilder*) builder;
+ (KeypressEventBuilder*) builderWithPrototype:(KeypressEvent*) prototype;
- (KeypressEventBuilder*) toBuilder;

+ (KeypressEvent*) parseFromData:(NSData*) data;
+ (KeypressEvent*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (KeypressEvent*) parseFromInputStream:(NSInputStream*) input;
+ (KeypressEvent*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (KeypressEvent*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (KeypressEvent*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface KeypressEventBuilder : PBGeneratedMessageBuilder {
@private
  KeypressEvent* resultKeypressEvent;
}

- (KeypressEvent*) defaultInstance;

- (KeypressEventBuilder*) clear;
- (KeypressEventBuilder*) clone;

- (KeypressEvent*) build;
- (KeypressEvent*) buildPartial;

- (KeypressEventBuilder*) mergeFrom:(KeypressEvent*) other;
- (KeypressEventBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (KeypressEventBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasState;
- (KeypressEventState) state;
- (KeypressEventBuilder*) setState:(KeypressEventState) value;
- (KeypressEventBuilder*) clearState;

- (BOOL) hasKeycode;
- (SInt32) keycode;
- (KeypressEventBuilder*) setKeycode:(SInt32) value;
- (KeypressEventBuilder*) clearKeycode;
@end

@interface GestureEvent : PBGeneratedMessage {
@private
  BOOL hasLocationX_:1;
  BOOL hasLocationY_:1;
  BOOL hasPinchScale_:1;
  BOOL hasPinchVelocity_:1;
  BOOL hasPanTranslationX_:1;
  BOOL hasPanTranslationY_:1;
  BOOL hasPanVelocityX_:1;
  BOOL hasPanVelocityY_:1;
  BOOL hasRotationAngle_:1;
  BOOL hasRotationVelocity_:1;
  BOOL hasPressDuration_:1;
  BOOL hasTapCount_:1;
  BOOL hasType_:1;
  BOOL hasState_:1;
  BOOL hasSwipeDirection_:1;
  BOOL hasCircleDirection_:1;
  Float32 locationX;
  Float32 locationY;
  Float32 pinchScale;
  Float32 pinchVelocity;
  Float32 panTranslationX;
  Float32 panTranslationY;
  Float32 panVelocityX;
  Float32 panVelocityY;
  Float32 rotationAngle;
  Float32 rotationVelocity;
  SInt64 pressDuration;
  SInt32 tapCount;
  GestureEventType type;
  GestureEventState state;
  GestureEventSwipeDirection swipeDirection;
  GestureEventCircleDirection circleDirection;
}
- (BOOL) hasLocationX;
- (BOOL) hasLocationY;
- (BOOL) hasType;
- (BOOL) hasState;
- (BOOL) hasTapCount;
- (BOOL) hasPinchScale;
- (BOOL) hasPinchVelocity;
- (BOOL) hasPanTranslationX;
- (BOOL) hasPanTranslationY;
- (BOOL) hasPanVelocityX;
- (BOOL) hasPanVelocityY;
- (BOOL) hasSwipeDirection;
- (BOOL) hasRotationAngle;
- (BOOL) hasRotationVelocity;
- (BOOL) hasPressDuration;
- (BOOL) hasCircleDirection;
@property (readonly) Float32 locationX;
@property (readonly) Float32 locationY;
@property (readonly) GestureEventType type;
@property (readonly) GestureEventState state;
@property (readonly) SInt32 tapCount;
@property (readonly) Float32 pinchScale;
@property (readonly) Float32 pinchVelocity;
@property (readonly) Float32 panTranslationX;
@property (readonly) Float32 panTranslationY;
@property (readonly) Float32 panVelocityX;
@property (readonly) Float32 panVelocityY;
@property (readonly) GestureEventSwipeDirection swipeDirection;
@property (readonly) Float32 rotationAngle;
@property (readonly) Float32 rotationVelocity;
@property (readonly) SInt64 pressDuration;
@property (readonly) GestureEventCircleDirection circleDirection;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

+ (id<PBExtensionField>) event;
- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (GestureEventBuilder*) builder;
+ (GestureEventBuilder*) builder;
+ (GestureEventBuilder*) builderWithPrototype:(GestureEvent*) prototype;
- (GestureEventBuilder*) toBuilder;

+ (GestureEvent*) parseFromData:(NSData*) data;
+ (GestureEvent*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GestureEvent*) parseFromInputStream:(NSInputStream*) input;
+ (GestureEvent*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GestureEvent*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (GestureEvent*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface GestureEventBuilder : PBGeneratedMessageBuilder {
@private
  GestureEvent* resultGestureEvent;
}

- (GestureEvent*) defaultInstance;

- (GestureEventBuilder*) clear;
- (GestureEventBuilder*) clone;

- (GestureEvent*) build;
- (GestureEvent*) buildPartial;

- (GestureEventBuilder*) mergeFrom:(GestureEvent*) other;
- (GestureEventBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (GestureEventBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasLocationX;
- (Float32) locationX;
- (GestureEventBuilder*) setLocationX:(Float32) value;
- (GestureEventBuilder*) clearLocationX;

- (BOOL) hasLocationY;
- (Float32) locationY;
- (GestureEventBuilder*) setLocationY:(Float32) value;
- (GestureEventBuilder*) clearLocationY;

- (BOOL) hasType;
- (GestureEventType) type;
- (GestureEventBuilder*) setType:(GestureEventType) value;
- (GestureEventBuilder*) clearType;

- (BOOL) hasState;
- (GestureEventState) state;
- (GestureEventBuilder*) setState:(GestureEventState) value;
- (GestureEventBuilder*) clearState;

- (BOOL) hasTapCount;
- (SInt32) tapCount;
- (GestureEventBuilder*) setTapCount:(SInt32) value;
- (GestureEventBuilder*) clearTapCount;

- (BOOL) hasPinchScale;
- (Float32) pinchScale;
- (GestureEventBuilder*) setPinchScale:(Float32) value;
- (GestureEventBuilder*) clearPinchScale;

- (BOOL) hasPinchVelocity;
- (Float32) pinchVelocity;
- (GestureEventBuilder*) setPinchVelocity:(Float32) value;
- (GestureEventBuilder*) clearPinchVelocity;

- (BOOL) hasPanTranslationX;
- (Float32) panTranslationX;
- (GestureEventBuilder*) setPanTranslationX:(Float32) value;
- (GestureEventBuilder*) clearPanTranslationX;

- (BOOL) hasPanTranslationY;
- (Float32) panTranslationY;
- (GestureEventBuilder*) setPanTranslationY:(Float32) value;
- (GestureEventBuilder*) clearPanTranslationY;

- (BOOL) hasPanVelocityX;
- (Float32) panVelocityX;
- (GestureEventBuilder*) setPanVelocityX:(Float32) value;
- (GestureEventBuilder*) clearPanVelocityX;

- (BOOL) hasPanVelocityY;
- (Float32) panVelocityY;
- (GestureEventBuilder*) setPanVelocityY:(Float32) value;
- (GestureEventBuilder*) clearPanVelocityY;

- (BOOL) hasSwipeDirection;
- (GestureEventSwipeDirection) swipeDirection;
- (GestureEventBuilder*) setSwipeDirection:(GestureEventSwipeDirection) value;
- (GestureEventBuilder*) clearSwipeDirection;

- (BOOL) hasRotationAngle;
- (Float32) rotationAngle;
- (GestureEventBuilder*) setRotationAngle:(Float32) value;
- (GestureEventBuilder*) clearRotationAngle;

- (BOOL) hasRotationVelocity;
- (Float32) rotationVelocity;
- (GestureEventBuilder*) setRotationVelocity:(Float32) value;
- (GestureEventBuilder*) clearRotationVelocity;

- (BOOL) hasPressDuration;
- (SInt64) pressDuration;
- (GestureEventBuilder*) setPressDuration:(SInt64) value;
- (GestureEventBuilder*) clearPressDuration;

- (BOOL) hasCircleDirection;
- (GestureEventCircleDirection) circleDirection;
- (GestureEventBuilder*) setCircleDirection:(GestureEventCircleDirection) value;
- (GestureEventBuilder*) clearCircleDirection;
@end

@interface HandMotionEvent : PBGeneratedMessage {
@private
  BOOL hasLocationX_:1;
  BOOL hasLocationY_:1;
  BOOL hasPitch_:1;
  BOOL hasYaw_:1;
  BOOL hasRoll_:1;
  BOOL hasState_:1;
  BOOL hasPhase_:1;
  Float32 locationX;
  Float32 locationY;
  Float32 pitch;
  Float32 yaw;
  Float32 roll;
  HandMotionEventState state;
  Phase phase;
}
- (BOOL) hasLocationX;
- (BOOL) hasLocationY;
- (BOOL) hasState;
- (BOOL) hasPhase;
- (BOOL) hasPitch;
- (BOOL) hasYaw;
- (BOOL) hasRoll;
@property (readonly) Float32 locationX;
@property (readonly) Float32 locationY;
@property (readonly) HandMotionEventState state;
@property (readonly) Phase phase;
@property (readonly) Float32 pitch;
@property (readonly) Float32 yaw;
@property (readonly) Float32 roll;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

+ (id<PBExtensionField>) event;
- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (HandMotionEventBuilder*) builder;
+ (HandMotionEventBuilder*) builder;
+ (HandMotionEventBuilder*) builderWithPrototype:(HandMotionEvent*) prototype;
- (HandMotionEventBuilder*) toBuilder;

+ (HandMotionEvent*) parseFromData:(NSData*) data;
+ (HandMotionEvent*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (HandMotionEvent*) parseFromInputStream:(NSInputStream*) input;
+ (HandMotionEvent*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (HandMotionEvent*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (HandMotionEvent*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface HandMotionEventBuilder : PBGeneratedMessageBuilder {
@private
  HandMotionEvent* resultHandMotionEvent;
}

- (HandMotionEvent*) defaultInstance;

- (HandMotionEventBuilder*) clear;
- (HandMotionEventBuilder*) clone;

- (HandMotionEvent*) build;
- (HandMotionEvent*) buildPartial;

- (HandMotionEventBuilder*) mergeFrom:(HandMotionEvent*) other;
- (HandMotionEventBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (HandMotionEventBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasLocationX;
- (Float32) locationX;
- (HandMotionEventBuilder*) setLocationX:(Float32) value;
- (HandMotionEventBuilder*) clearLocationX;

- (BOOL) hasLocationY;
- (Float32) locationY;
- (HandMotionEventBuilder*) setLocationY:(Float32) value;
- (HandMotionEventBuilder*) clearLocationY;

- (BOOL) hasState;
- (HandMotionEventState) state;
- (HandMotionEventBuilder*) setState:(HandMotionEventState) value;
- (HandMotionEventBuilder*) clearState;

- (BOOL) hasPhase;
- (Phase) phase;
- (HandMotionEventBuilder*) setPhase:(Phase) value;
- (HandMotionEventBuilder*) clearPhase;

- (BOOL) hasPitch;
- (Float32) pitch;
- (HandMotionEventBuilder*) setPitch:(Float32) value;
- (HandMotionEventBuilder*) clearPitch;

- (BOOL) hasYaw;
- (Float32) yaw;
- (HandMotionEventBuilder*) setYaw:(Float32) value;
- (HandMotionEventBuilder*) clearYaw;

- (BOOL) hasRoll;
- (Float32) roll;
- (HandMotionEventBuilder*) setRoll:(Float32) value;
- (HandMotionEventBuilder*) clearRoll;
@end

@interface OAuthRequestEvent : PBGeneratedMessage {
@private
  BOOL hasAuthUrl_:1;
  NSString* authUrl;
}
- (BOOL) hasAuthUrl;
@property (readonly, strong) NSString* authUrl;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

+ (id<PBExtensionField>) event;
- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (OAuthRequestEventBuilder*) builder;
+ (OAuthRequestEventBuilder*) builder;
+ (OAuthRequestEventBuilder*) builderWithPrototype:(OAuthRequestEvent*) prototype;
- (OAuthRequestEventBuilder*) toBuilder;

+ (OAuthRequestEvent*) parseFromData:(NSData*) data;
+ (OAuthRequestEvent*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (OAuthRequestEvent*) parseFromInputStream:(NSInputStream*) input;
+ (OAuthRequestEvent*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (OAuthRequestEvent*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (OAuthRequestEvent*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface OAuthRequestEventBuilder : PBGeneratedMessageBuilder {
@private
  OAuthRequestEvent* resultOauthRequestEvent;
}

- (OAuthRequestEvent*) defaultInstance;

- (OAuthRequestEventBuilder*) clear;
- (OAuthRequestEventBuilder*) clone;

- (OAuthRequestEvent*) build;
- (OAuthRequestEvent*) buildPartial;

- (OAuthRequestEventBuilder*) mergeFrom:(OAuthRequestEvent*) other;
- (OAuthRequestEventBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (OAuthRequestEventBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasAuthUrl;
- (NSString*) authUrl;
- (OAuthRequestEventBuilder*) setAuthUrl:(NSString*) value;
- (OAuthRequestEventBuilder*) clearAuthUrl;
@end

@interface OAuthResponseEvent : PBGeneratedMessage {
@private
  BOOL hasAuthCode_:1;
  NSString* authCode;
}
- (BOOL) hasAuthCode;
@property (readonly, strong) NSString* authCode;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

+ (id<PBExtensionField>) event;
- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (OAuthResponseEventBuilder*) builder;
+ (OAuthResponseEventBuilder*) builder;
+ (OAuthResponseEventBuilder*) builderWithPrototype:(OAuthResponseEvent*) prototype;
- (OAuthResponseEventBuilder*) toBuilder;

+ (OAuthResponseEvent*) parseFromData:(NSData*) data;
+ (OAuthResponseEvent*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (OAuthResponseEvent*) parseFromInputStream:(NSInputStream*) input;
+ (OAuthResponseEvent*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (OAuthResponseEvent*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (OAuthResponseEvent*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface OAuthResponseEventBuilder : PBGeneratedMessageBuilder {
@private
  OAuthResponseEvent* resultOauthResponseEvent;
}

- (OAuthResponseEvent*) defaultInstance;

- (OAuthResponseEventBuilder*) clear;
- (OAuthResponseEventBuilder*) clone;

- (OAuthResponseEvent*) build;
- (OAuthResponseEvent*) buildPartial;

- (OAuthResponseEventBuilder*) mergeFrom:(OAuthResponseEvent*) other;
- (OAuthResponseEventBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (OAuthResponseEventBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasAuthCode;
- (NSString*) authCode;
- (OAuthResponseEventBuilder*) setAuthCode:(NSString*) value;
- (OAuthResponseEventBuilder*) clearAuthCode;
@end

@interface WifiNetwork : PBGeneratedMessage {
@private
  BOOL hasStrength_:1;
  BOOL hasSsid_:1;
  BOOL hasBssid_:1;
  BOOL hasCapabilities_:1;
  SInt32 strength;
  NSString* ssid;
  NSString* bssid;
  NSString* capabilities;
}
- (BOOL) hasSsid;
- (BOOL) hasStrength;
- (BOOL) hasBssid;
- (BOOL) hasCapabilities;
@property (readonly, strong) NSString* ssid;
@property (readonly) SInt32 strength;
@property (readonly, strong) NSString* bssid;
@property (readonly, strong) NSString* capabilities;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (WifiNetworkBuilder*) builder;
+ (WifiNetworkBuilder*) builder;
+ (WifiNetworkBuilder*) builderWithPrototype:(WifiNetwork*) prototype;
- (WifiNetworkBuilder*) toBuilder;

+ (WifiNetwork*) parseFromData:(NSData*) data;
+ (WifiNetwork*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (WifiNetwork*) parseFromInputStream:(NSInputStream*) input;
+ (WifiNetwork*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (WifiNetwork*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (WifiNetwork*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface WifiNetworkBuilder : PBGeneratedMessageBuilder {
@private
  WifiNetwork* resultWifiNetwork;
}

- (WifiNetwork*) defaultInstance;

- (WifiNetworkBuilder*) clear;
- (WifiNetworkBuilder*) clone;

- (WifiNetwork*) build;
- (WifiNetwork*) buildPartial;

- (WifiNetworkBuilder*) mergeFrom:(WifiNetwork*) other;
- (WifiNetworkBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (WifiNetworkBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSsid;
- (NSString*) ssid;
- (WifiNetworkBuilder*) setSsid:(NSString*) value;
- (WifiNetworkBuilder*) clearSsid;

- (BOOL) hasStrength;
- (SInt32) strength;
- (WifiNetworkBuilder*) setStrength:(SInt32) value;
- (WifiNetworkBuilder*) clearStrength;

- (BOOL) hasBssid;
- (NSString*) bssid;
- (WifiNetworkBuilder*) setBssid:(NSString*) value;
- (WifiNetworkBuilder*) clearBssid;

- (BOOL) hasCapabilities;
- (NSString*) capabilities;
- (WifiNetworkBuilder*) setCapabilities:(NSString*) value;
- (WifiNetworkBuilder*) clearCapabilities;
@end

@interface SetupRequestEvent : PBGeneratedMessage {
@private
  BOOL hasBack_:1;
  BOOL hasName_:1;
  BOOL hasSsid_:1;
  BOOL hasPassword_:1;
  BOOL hasPhase_:1;
  BOOL back_:1;
  NSString* name;
  NSString* ssid;
  NSString* password;
  SetupPhase phase;
}
- (BOOL) hasPhase;
- (BOOL) hasName;
- (BOOL) hasSsid;
- (BOOL) hasPassword;
- (BOOL) hasBack;
@property (readonly) SetupPhase phase;
@property (readonly, strong) NSString* name;
@property (readonly, strong) NSString* ssid;
@property (readonly, strong) NSString* password;
- (BOOL) back;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

+ (id<PBExtensionField>) event;
- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SetupRequestEventBuilder*) builder;
+ (SetupRequestEventBuilder*) builder;
+ (SetupRequestEventBuilder*) builderWithPrototype:(SetupRequestEvent*) prototype;
- (SetupRequestEventBuilder*) toBuilder;

+ (SetupRequestEvent*) parseFromData:(NSData*) data;
+ (SetupRequestEvent*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SetupRequestEvent*) parseFromInputStream:(NSInputStream*) input;
+ (SetupRequestEvent*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SetupRequestEvent*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SetupRequestEvent*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SetupRequestEventBuilder : PBGeneratedMessageBuilder {
@private
  SetupRequestEvent* resultSetupRequestEvent;
}

- (SetupRequestEvent*) defaultInstance;

- (SetupRequestEventBuilder*) clear;
- (SetupRequestEventBuilder*) clone;

- (SetupRequestEvent*) build;
- (SetupRequestEvent*) buildPartial;

- (SetupRequestEventBuilder*) mergeFrom:(SetupRequestEvent*) other;
- (SetupRequestEventBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SetupRequestEventBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPhase;
- (SetupPhase) phase;
- (SetupRequestEventBuilder*) setPhase:(SetupPhase) value;
- (SetupRequestEventBuilder*) clearPhase;

- (BOOL) hasName;
- (NSString*) name;
- (SetupRequestEventBuilder*) setName:(NSString*) value;
- (SetupRequestEventBuilder*) clearName;

- (BOOL) hasSsid;
- (NSString*) ssid;
- (SetupRequestEventBuilder*) setSsid:(NSString*) value;
- (SetupRequestEventBuilder*) clearSsid;

- (BOOL) hasPassword;
- (NSString*) password;
- (SetupRequestEventBuilder*) setPassword:(NSString*) value;
- (SetupRequestEventBuilder*) clearPassword;

- (BOOL) hasBack;
- (BOOL) back;
- (SetupRequestEventBuilder*) setBack:(BOOL) value;
- (SetupRequestEventBuilder*) clearBack;
@end

@interface SetupResponseEvent : PBGeneratedMessage {
@private
  BOOL hasError_:1;
  BOOL hasErrorMessage_:1;
  BOOL hasCode_:1;
  BOOL hasPhase_:1;
  BOOL error_:1;
  NSString* errorMessage;
  NSString* code;
  SetupPhase phase;
  NSMutableArray * wifiNetworksArray;
}
- (BOOL) hasPhase;
- (BOOL) hasError;
- (BOOL) hasErrorMessage;
- (BOOL) hasCode;
@property (readonly) SetupPhase phase;
- (BOOL) error;
@property (readonly, strong) NSString* errorMessage;
@property (readonly, strong) NSString* code;
@property (readonly, strong) NSArray * wifiNetworks;
- (WifiNetwork*)wifiNetworksAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

+ (id<PBExtensionField>) event;
- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SetupResponseEventBuilder*) builder;
+ (SetupResponseEventBuilder*) builder;
+ (SetupResponseEventBuilder*) builderWithPrototype:(SetupResponseEvent*) prototype;
- (SetupResponseEventBuilder*) toBuilder;

+ (SetupResponseEvent*) parseFromData:(NSData*) data;
+ (SetupResponseEvent*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SetupResponseEvent*) parseFromInputStream:(NSInputStream*) input;
+ (SetupResponseEvent*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SetupResponseEvent*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SetupResponseEvent*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SetupResponseEventBuilder : PBGeneratedMessageBuilder {
@private
  SetupResponseEvent* resultSetupResponseEvent;
}

- (SetupResponseEvent*) defaultInstance;

- (SetupResponseEventBuilder*) clear;
- (SetupResponseEventBuilder*) clone;

- (SetupResponseEvent*) build;
- (SetupResponseEvent*) buildPartial;

- (SetupResponseEventBuilder*) mergeFrom:(SetupResponseEvent*) other;
- (SetupResponseEventBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SetupResponseEventBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPhase;
- (SetupPhase) phase;
- (SetupResponseEventBuilder*) setPhase:(SetupPhase) value;
- (SetupResponseEventBuilder*) clearPhase;

- (BOOL) hasError;
- (BOOL) error;
- (SetupResponseEventBuilder*) setError:(BOOL) value;
- (SetupResponseEventBuilder*) clearError;

- (BOOL) hasErrorMessage;
- (NSString*) errorMessage;
- (SetupResponseEventBuilder*) setErrorMessage:(NSString*) value;
- (SetupResponseEventBuilder*) clearErrorMessage;

- (BOOL) hasCode;
- (NSString*) code;
- (SetupResponseEventBuilder*) setCode:(NSString*) value;
- (SetupResponseEventBuilder*) clearCode;

- (NSMutableArray *)wifiNetworks;
- (WifiNetwork*)wifiNetworksAtIndex:(NSUInteger)index;
- (SetupResponseEventBuilder *)addWifiNetworks:(WifiNetwork*)value;
- (SetupResponseEventBuilder *)setWifiNetworksArray:(NSArray *)array;
- (SetupResponseEventBuilder *)clearWifiNetworks;
@end

@interface TextInputRequestEvent : PBGeneratedMessage {
@private
  BOOL hasMaxLength_:1;
  BOOL hasType_:1;
  SInt32 maxLength;
  TextInputRequestEventType type;
}
- (BOOL) hasType;
- (BOOL) hasMaxLength;
@property (readonly) TextInputRequestEventType type;
@property (readonly) SInt32 maxLength;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

+ (id<PBExtensionField>) event;
- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TextInputRequestEventBuilder*) builder;
+ (TextInputRequestEventBuilder*) builder;
+ (TextInputRequestEventBuilder*) builderWithPrototype:(TextInputRequestEvent*) prototype;
- (TextInputRequestEventBuilder*) toBuilder;

+ (TextInputRequestEvent*) parseFromData:(NSData*) data;
+ (TextInputRequestEvent*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TextInputRequestEvent*) parseFromInputStream:(NSInputStream*) input;
+ (TextInputRequestEvent*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TextInputRequestEvent*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TextInputRequestEvent*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TextInputRequestEventBuilder : PBGeneratedMessageBuilder {
@private
  TextInputRequestEvent* resultTextInputRequestEvent;
}

- (TextInputRequestEvent*) defaultInstance;

- (TextInputRequestEventBuilder*) clear;
- (TextInputRequestEventBuilder*) clone;

- (TextInputRequestEvent*) build;
- (TextInputRequestEvent*) buildPartial;

- (TextInputRequestEventBuilder*) mergeFrom:(TextInputRequestEvent*) other;
- (TextInputRequestEventBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TextInputRequestEventBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasType;
- (TextInputRequestEventType) type;
- (TextInputRequestEventBuilder*) setType:(TextInputRequestEventType) value;
- (TextInputRequestEventBuilder*) clearType;

- (BOOL) hasMaxLength;
- (SInt32) maxLength;
- (TextInputRequestEventBuilder*) setMaxLength:(SInt32) value;
- (TextInputRequestEventBuilder*) clearMaxLength;
@end

@interface TextInputResponseEvent : PBGeneratedMessage {
@private
  BOOL hasEncrypted_:1;
  BOOL hasText_:1;
  BOOL hasState_:1;
  BOOL encrypted_:1;
  NSString* text;
  TextInputResponseEventState state;
}
- (BOOL) hasState;
- (BOOL) hasText;
- (BOOL) hasEncrypted;
@property (readonly) TextInputResponseEventState state;
@property (readonly, strong) NSString* text;
- (BOOL) encrypted;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

+ (id<PBExtensionField>) event;
- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TextInputResponseEventBuilder*) builder;
+ (TextInputResponseEventBuilder*) builder;
+ (TextInputResponseEventBuilder*) builderWithPrototype:(TextInputResponseEvent*) prototype;
- (TextInputResponseEventBuilder*) toBuilder;

+ (TextInputResponseEvent*) parseFromData:(NSData*) data;
+ (TextInputResponseEvent*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TextInputResponseEvent*) parseFromInputStream:(NSInputStream*) input;
+ (TextInputResponseEvent*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TextInputResponseEvent*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TextInputResponseEvent*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TextInputResponseEventBuilder : PBGeneratedMessageBuilder {
@private
  TextInputResponseEvent* resultTextInputResponseEvent;
}

- (TextInputResponseEvent*) defaultInstance;

- (TextInputResponseEventBuilder*) clear;
- (TextInputResponseEventBuilder*) clone;

- (TextInputResponseEvent*) build;
- (TextInputResponseEvent*) buildPartial;

- (TextInputResponseEventBuilder*) mergeFrom:(TextInputResponseEvent*) other;
- (TextInputResponseEventBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TextInputResponseEventBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasState;
- (TextInputResponseEventState) state;
- (TextInputResponseEventBuilder*) setState:(TextInputResponseEventState) value;
- (TextInputResponseEventBuilder*) clearState;

- (BOOL) hasText;
- (NSString*) text;
- (TextInputResponseEventBuilder*) setText:(NSString*) value;
- (TextInputResponseEventBuilder*) clearText;

- (BOOL) hasEncrypted;
- (BOOL) encrypted;
- (TextInputResponseEventBuilder*) setEncrypted:(BOOL) value;
- (TextInputResponseEventBuilder*) clearEncrypted;
@end

@interface FunctionEvent : PBGeneratedMessage {
@private
  BOOL hasKey_:1;
  FunctionEventKey key;
}
- (BOOL) hasKey;
@property (readonly) FunctionEventKey key;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

+ (id<PBExtensionField>) event;
- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FunctionEventBuilder*) builder;
+ (FunctionEventBuilder*) builder;
+ (FunctionEventBuilder*) builderWithPrototype:(FunctionEvent*) prototype;
- (FunctionEventBuilder*) toBuilder;

+ (FunctionEvent*) parseFromData:(NSData*) data;
+ (FunctionEvent*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FunctionEvent*) parseFromInputStream:(NSInputStream*) input;
+ (FunctionEvent*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FunctionEvent*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FunctionEvent*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FunctionEventBuilder : PBGeneratedMessageBuilder {
@private
  FunctionEvent* resultFunctionEvent;
}

- (FunctionEvent*) defaultInstance;

- (FunctionEventBuilder*) clear;
- (FunctionEventBuilder*) clone;

- (FunctionEvent*) build;
- (FunctionEvent*) buildPartial;

- (FunctionEventBuilder*) mergeFrom:(FunctionEvent*) other;
- (FunctionEventBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FunctionEventBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasKey;
- (FunctionEventKey) key;
- (FunctionEventBuilder*) setKey:(FunctionEventKey) value;
- (FunctionEventBuilder*) clearKey;
@end


// @@protoc_insertion_point(global_scope)
